### ISSUE TITLE
[Discussion] How to represent a flattened enum?

### ISSUE THREAD

**Issue by Ploppz** [novifinancial/serde-reflection#12]
Example:

```rust
#[derive(Serialize, Deserialize)]
struct StructA {
    #[serde(flatten)]
    pub bar: EnumA,
    pub z: i32,
}

#[derive(Serialize, Deserialize)]
#[serde(tag = "type")]
enum EnumA {
    One {x: i32},
    Two {y: i32}
}

```

In JSON it could serialize as for example:
```json
{
    "z": 5,
    "type": "One",
    "x": 6
}
```
or
```json
{
    "z": 7,
    "type": "Two",
    "y": 8
}
```

I guess the simplest solution, which is also possible atm, is to just let the format of StructA consist of _optional_ `x` and `y`, and let "type" be an enum with unit variants `One` and `Two`.
Information about the grouping of variables for different variants of the enum is lost this way ("if type is One, x is present, ...").
But I don't know if there are a lot of use cases that would even support that kind of information. Personally I'm working towards OpenAPI specification of a JSON API.

**Comment by matbd** [comment]
I guess it makes sense but I cannot speak for your use case. Note that `serde_reflection::*Format` does not track whether a field has a default value. (Currently, in applications, we assume that all fields are required.)

JSON schemas look so different from the Serde data model. In the long run, I'm curious how far you can go with serde-reflection (and specifically the AST `serde_reflection::*Format`).

**Comment by Ploppz** [comment]
> Note that `serde_reflection::*Format` does not track whether a field has a default value. (Currently, in applications, we assume that all fields are required.)

In case there is a misunderstanding; we won't need any default value in this case. `"type"` is a little special as it is basically a new enum separate from `EnumA` that has all its variants but without any fields, and is represented as a string (`"One"`, `"Two"`). As a start though I'll just say that "type" is an arbitrary string in the format.

As for `"x"` and `"y"` these would be Optional (without any default value).

> In the long run, I'm curious how far you can go with serde-reflection (and specifically the AST `serde_reflection::*Format`).
I would hope that the Format structs could be adapted if things are needed for the JSON use-case. Or do you think we just need a different crate for self-describing formats? In my proc macro system, the only thing I use from `serde-reflection` is Format. Thought it would be nice to try to converge efforts to a general library.

**Comment by matbd** [comment]
For doc comments, I was planning to experiment with the crate [structdoc](https://docs.rs/structdoc/0.1.4/structdoc/) at some point. It seems to support Serde attributes such as `rename` and `flatten`(for you :)). The fact that it supports `rename` means that reconciling data from `structdoc` and `serde-reflection` should be relatively easy.

In my mind, the definitions (`serde_reflection::*Format`) are meant to support the specific runtime analysis in the same crate (`serde_reflection::Tracer`). It should not be too hard to duplicate these definitions in a new crate and enrich the AST with inputs coming from different kind of analysis (for instance structdoc). I may end up needing this myself at some point for our use case but I'm not sure when this is going to happen.

**Comment by matbd** [comment]
The README should hopefully make it a bit more clear that this project is mainly intended for binary formats such as bincode and LCS.

p.s. I added support for custom comments since then.
