### ISSUE TITLE
[Feature Request]Support Javascript

### ISSUE THREAD

**Issue by jolestar** [novifinancial/serde-reflection#29]
# 🚀 Feature Request

## Motivation

Please support Javascript for call libra jsonrpc API in javascript.

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by mimoo** [comment]
note that this is probably not too hard to do if we support rust-generated web assembly

**Comment by matbd** [comment]
@jolestar Encoding Rust datatypes into idiomatic Javascript could be challenging for someone like me who never worked in Javascript. I believe BuckleScript has developed such a mapping for Ocaml types, so I'd be very tempted to target ReasonML if we go for it: https://reasonml.org/docs/reason-compiler/latest/common-data-types

**Comment by jolestar** [comment]
@matbd How about Typescript? I haven't used BuckleScript and don't know how compatible it is with Javascript, but Typescript is great for mapping between strongly-typed languages and Javascript.

**Comment by matbd** [comment]
The link I pasted ^^ lists the target Javascript types for Ocaml types (Rust types would be likely similar).

Typescript is indeed another possibility. I need to study this more closely.

**Comment by mimoo** [comment]
@matbd why target any of these if we can generate js from rust-generated wasm?

**Comment by matbd** [comment]
@mimoo Rust compiled to wasm is still one [FFI](https://hacks.mozilla.org/2018/04/javascript-to-rust-and-back-again-a-wasm-bindgen-tale) away from JS.

**Comment by mimoo** [comment]
you can convert wasm to JS
