### ISSUE TITLE
[Feature Request] Support f32 and f64 for python using struct

### ISSUE THREAD

**Issue by tobni** [novifinancial/serde-reflection#40]
# 🚀 Feature Request

Support `f32` and `f64` (double) floating point types for `serdegen` python codegen.
## Motivation

I believe supporting all available numerical primitives in rust is attractive for the feature-completeness of the python/rust interop for this project. 

## Pitch

**Describe the solution you'd like**

Python standard library module [struct](https://docs.python.org/3/library/struct.html) support byte-unpacking and packing of floating-point (floats and doubles) numbers following the IEEE-754 standard, and supports explicit endianess.

**Describe alternatives you've considered**

Only alternative is to use different implementation for parsing floats, or leave it as is to users to patch the generated code.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
I currently apply these changes via a git diff patch to the serdegen tool code output in my personal projects.
I could create a pr for this feature.

**Comment by matbd** [comment]
Sure, this sounds like a reasonable feature to add to the bincode runtime(s). (Note that the codegen itself is already doing the right thing.) Let me send a PR shortly for python.

**Comment by matbd** [comment]
@tobni This is now available in serde-generate 0.15.2 . Thanks for your patience!
