### ISSUE TITLE
[Feature Request] Add C# Code Generation

### ISSUE THREAD

**Issue by mattico** [novifinancial/serde-reflection#68]
# 🚀 Feature Request

Add code generation support for C#.

## Motivation

C# is a very popular language, which would be nice to support. I need support for it for my own project.

## Pitch

C# is rather similar to Java, so implementing it is a fairly straightforward port of the existing Java code generator.

I'm currently working on implementing this here: https://github.com/mattico/serde-reflection/tree/csharp
I would like to upstream this support if there is a desire for it.

**Comment by matbd** [comment]
Thanks for the feature request. C# has been on our radar for some time. I will be happy to review a PR based on the Java codegen.
