### ISSUE TITLE
How to serialize chrono::DateTime?

### ISSUE THREAD

**Issue by hoang17** [novifinancial/serde-reflection#79]
Hi, is there a way to serialize a struct with `chrono::DateTime` field? My current workaround is to use `String` but it seems not optimal.
Here is an example:

```
pub struct User {
    pub id: i32,
    pub email: String,
    pub last_login: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}
```

It would be great if `serde-generate` can convert `chrono::DateTime` to golang `time.Time`

Thanks a lot!

**Comment by matbd** [comment]
Indeed, it looks like `chrono::DateTime` gets serialized as a RFC3339 string by default (see https://serde.rs/custom-date-format.html).

Over the wire I would personally use an integer representing some form of unix timestamp https://docs.rs/chrono/0.4.19/chrono/struct.DateTime.html#method.timestamp

Anyways, to obtain a "class" instead of a primitive type in the generated code, you may define your own Rust type and annotate the fields so that serde-reflection sees a different wire format:
```
// Modified example after https://serde.rs/custom-date-format.html
// (Not tested)

pub struct User {
    pub id: i32,
    pub email: String,
    #[serde(with = "my_date_format")]
    pub last_login: Option<DateTime<Utc>>,
    #[serde(with = "my_date_format")]
    pub created_at: DateTime<Utc>,
    #[serde(with = "my_date_format")]
    pub updated_at: DateTime<Utc>,
}

#[derive(Serialize, Deserialize)]
struct UnixTime(i64);

mod my_date_format {
    pub fn serialize<S>(
        date: &DateTime<Utc>,
        serializer: S,
    ) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        UnixTime(date.timestamp()).serialize(serializer)
    }
    
    pub fn deserialize<'de, D>(
        deserializer: D,
    ) -> Result<DateTime<Utc>, D::Error>
    where
        D: Deserializer<'de>,
    {
        UnixTime::deserialize(deserializer).map(|time| Utc.timestamp_millis(time.0))
    }
}
``

**Comment by matbd** [comment]
I'm going to close this issue.

For the records, the library API of `serde-generate` provides an experimental way of injecting custom code inside generated user classes in each language. Arguably, this is not very useful in Go (where adding methods to an existing class is trivial) but if there is some interest for other languages, we could make the feature available as a command-line option of the tool `serdegen`.

**Comment by hoang17** [comment]
Cool, thanks a lot for your help!
