### ISSUE TITLE
[Feature Request] JSON Scheme

### ISSUE THREAD

**Issue by Simon-Laux** [novifinancial/serde-reflection#90]
# 🚀 Feature Request

Generating a json scheme that matches what serde_json expects/generates.

## Motivation

I have a json rpc - like api where I do this in typescript:
```ts
function add(a:number, b:number) {
  call("command_id", {a, b})
}
```
which calls a function in rust, after the arguments object is de-serialized by serde:
```rust
#[derive(Deserialize, Debug)]
struct cmd_add_args {
    a: u32,
    b: u32,
}
fn add(args: cmd_add_args, invocation_id: u32) -> cmd_add_res {
    cmd_add_res {
        result: {
            let a = args.a;
            let b = args.b;
            {
                a + b
            }
        },
        invocation_id: invocation_id,
    }
}
```

now I'm looking if there is a way to get those type-definitions of the JSON objects generated by rust (first a json scheme that then can be converted into a ts type.) So I can either potentially generate the ts part or just use the generated typings to check if the typescript client is still in sync with the rust backend.

## Pitch

**Describe the solution you'd like**
Addition of json scheme as possible output of serde_generate.

**Describe alternatives you've considered**
manually writing/checking everything for now in my case, but there are other possible uses for this feature so it might still be relevant for others.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
No, not now at-least, because I'm too inexperienced to be comfortable coding in the quality this repo is in. (also I'm unsure about all edge cases and how serde_json works in detail)

**Comment by matbd** [comment]
I'm not a specialist of JSON schemas but after looking at [this page](https://json-schema.org/implementations.html), I would suggest one of those solutions instead:

1. Create sample JSON data using Serde (+ optionally a fuzzing library such as [arbitrary](https://docs.rs/arbitrary/1.0.0/arbitrary/)) then reconstruct a JSON schema using the proposed "schema from data" solutions (e.g. quicktype.io)

2. Write a JSON schema by hand then generate Rust code using [schemafy](https://github.com/Marwes/schemafy/)

It should also be noted that `serde-reflection` does not work with JSON-oriented attributes of Serde (e.g. [`#[serde(flatten)]`](https://serde.rs/attr-flatten.html#capture-additional-fields)) that deviate from the original [Serde data model](https://serde.rs/data-model.html). Therefore, the solution suggested in this PR would probably not be able to support a very satisfying subset of JSON schemas.
