### ISSUE TITLE
Support Dart

### ISSUE THREAD

**Issue by unicomp21** [novifinancial/serde-reflection#96]
Can we open up the discussions tab?  So folks can open w/ questions first?  Before opening an issue?

**Comment by matbd** [comment]
I suppose you have seen this PR: https://github.com/novifinancial/serde-reflection/pull/57

**Comment by kturney** [comment]
@unicomp21 FWIW, @jerel has a fork going at https://github.com/jerel/serde-reflection/tree/dart fleshing out the dart support.
